### ISSUE TITLE
Unittests failing with coverage

### ISSUE THREAD

**Issue by AbdealiJK** [ahupp/python-magic#105]
I was trying to run coverage on your unittests to find out how much was being tested. I found that when doing `coverage run test/test.py` one of the tests fail. (`test_descriptions` for 'test.gz')

```
$ coverage run test/test.py
F....
======================================================================
FAIL: test_descriptions (__main__.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test/test.py", line 62, in test_descriptions
    'text.txt': 'ASCII text',
  File "test/test.py", line 34, in assert_values
    self.assertTrue(False, "no match for " + repr(expected_value))
AssertionError: no match for ('gzip compressed data, was "test", from Unix, last modified: Sun Jun 29 01:32:52 2008', 'gzip compressed data, was "test", last modified: Sun Jun 29 01:32:52 2008, from Unix')

----------------------------------------------------------------------
Ran 5 tests in 0.080s

FAILED (failures=1)
Coverage.py warning: No data was collected.
```

Note that running it with `python` works.

```
$ python test/test.py
.....
----------------------------------------------------------------------
Ran 5 tests in 0.074s

OK
```

**Comment by AbdealiJK** [comment]
On more analysis. I was getting `gzip compressed data, was "test", from Unix, last modified: Sun Jun 29 07:02:52 2008` instead of the expected string (The timezone is wrong).

This is happening because `coverage` does not run the statements in the python file for tests. It only runs the unittest.TestCase class. The use of `os.environ['TZ'] = 'GMT'` is not a recommended usage, and test utilities like coverage, pytest, nose, etc do not support it.

**Comment by ahupp** [comment]
I'm having a hard time understanding how that would work - how does it import modules the test depends on then?

**Comment by AbdealiJK** [comment]
Hm, I've seen this happen in another project and this was the conclusion we came to there, but I can't seem to find any reference supporting this right now.

Although, as you brought it up, if I declare a global constant like "TEST_FILES", that is available inside the tests. So, I'm not sure how it works ! (maybe my analysis is completely wrong)

**Comment by AbdealiJK** [comment]
I began researching about this again, and found that I am mistaken. I tried this file:
```
import os
import unittest
os.environ['TZ'] = "GMT"
SOME_VAR = 1

class TestClass(unittest.TestCase):
    def test_cls_some_var(self):
        assert SOME_VAR == 1
    def test_cls_tz(self):
        assert os.environ['TZ'] == 'GMT'

if __name__ == "__main__":
    unittest.main(verbosity=2)
```
And it works with: `python test_cov.py`, `nosetests`, `py.test`, and `coverage run`.

But I still get the error for python-magic. On checking more, i found that `os.environ` is indeed set correctly inside the `test.py` for the test. But the test still fails >_<
Now I have no clue what the issue could be

**Comment by ahupp** [comment]
What happens if you run this?

    TZ=GMT coverage run test/test.py

**Comment by AbdealiJK** [comment]
That does work:
```
$ TZ=GMT coverage run test.py.....
----------------------------------------------------------------------
Ran 5 tests in 0.076s

OK
$ coverage report
Name                                                                                         Stmts   Miss  Cover
----------------------------------------------------------------------------------------------------------------
test.py                                                                                         56      3    95%
/venv/lib/python2.7/site-packages/magic.py                             151     26    83%
/venv/lib/python2.7/site-packages/pkg_resources/_vendor/six.py         444    442     1%
/venv/lib/python2.7/site-packages/pkg_resources/extern/__init__.py      35     32     9%
----------------------------------------------------------------------------------------------------------------
TOTAL                                                                                          686    503    27%

```

**Comment by fabaff** [comment]
This is still an issue:

OS: Fedora 31
Python: 3.7.5 (default, Dec 15 2019, 17:54:26) 

```bash
$ git clone git@github.com:fabaff/python-magic.git
Cloning into 'python-magic'...
remote: Enumerating objects: 25, done.
remote: Counting objects: 100% (25/25), done.
remote: Compressing objects: 100% (20/20), done.
remote: Total 641 (delta 9), reused 17 (delta 5), pack-reused 616
Receiving objects: 100% (641/641), 1.09 MiB | 776.00 KiB/s, done.
Resolving deltas: 100% (328/328), done.
$ cd python-magic/
$ python3 -m venv .
$ source bin/activate
(python-magic) [fab@test python-magic]$ python3 setup.py test
running test
running egg_info
creating python_magic.egg-info
writing python_magic.egg-info/PKG-INFO
writing dependency_links to python_magic.egg-info/dependency_links.txt
writing top-level names to python_magic.egg-info/top_level.txt
writing manifest file 'python_magic.egg-info/SOURCES.txt'
reading manifest file 'python_magic.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no directories found matching 'tests'
warning: no previously-included files matching '__pycache__' found anywhere in distribution
warning: no previously-included files matching '*.py[co]' found anywhere in distribution
writing manifest file 'python_magic.egg-info/SOURCES.txt'
running build_ext
test_descriptions (test.test.MagicTest) ... FAIL
test_errors (test.test.MagicTest) ... ok
test_from_buffer_str_and_bytes (test.test.MagicTest) ... ok
test_from_file_str_and_bytes (test.test.MagicTest) ... ok
test_getparam (test.test.MagicTest) ... ok
test_keep_going (test.test.MagicTest) ... ok
test_mime_encodings (test.test.MagicTest) ... ok
test_mime_types (test.test.MagicTest) ... ok
test_name_count (test.test.MagicTest) ... ok
test_rethrow (test.test.MagicTest) ... ok
test_unicode_result_nonraw (test.test.MagicTest) ... skipped "Magic file doesn't return expected type."
test_unicode_result_raw (test.test.MagicTest) ... skipped "Magic file doesn't return expected type."

======================================================================
FAIL: test_descriptions (test.test.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/fab/Documents/repos/python-magic/test/test.py", line 83, in test_descriptions
    }, buf_equals_file=False)
  File "/home/fab/Documents/repos/python-magic/test/test.py", line 34, in assert_values
    self.assertIn(value, expected_value)
AssertionError: 'gzip compressed data, was "test", last modified: Sun Jun 29 01:32:52 2008, from Unix, original size modulo 2^32 15' not found in ('gzip compressed data, was "test", from Unix, last modified: Sun Jun 29 01:32:52 2008', 'gzip compressed data, was "test", last modified: Sun Jun 29 01:32:52 2008, from Unix', 'gzip compressed data, was "test", last modified: Sun Jun 29 01:32:52 2008, from Unix, original size 15')

----------------------------------------------------------------------
Ran 12 tests in 0.050s

FAILED (failures=1, skipped=2)
Test failed: <unittest.runner.TextTestResult run=12 errors=0 failures=1>
error: Test failed: <unittest.runner.TextTestResult run=12 errors=0 failures=1>
```

I would be nice if this get addressed because if the tests don't pass the RPM build process is stopped.

**Comment by ahupp** [comment]
@fabaff I believe this is a different issue, where there are slight variations in libmagic output depending on version and magic file.  I've pushed an update that matches your output.

I'm not actually sure what happened with the origional coverage issue, it seems to work for me.

**Comment by ahupp** [comment]
repopening for origional issue

**Comment by ahupp** [comment]
@AbdealiJK I'm going to close since this is quite old and appears to work now.  Maybe a difference in the version of coverage?  Please re-open if you are still running into it.
