### ISSUE TITLE
ImportError: failed to find libmagic.  Check your installation 

### ISSUE THREAD

**Issue by ghost** [ahupp/python-magic#12]
install from latest source, it doesn't works on Mac OS X 10.6.8

``` sh
$ python --version
Python 2.6.7


$ port info python26
python26 @2.6.7 (lang)
Variants:             ucs4, (-)universal

Description:          Python is an interpreted, interactive, object-oriented programming language.
Homepage:             http://www.python.org/

Library Dependencies: gettext, zlib, openssl, sqlite3, db46, ncurses, gdbm, bzip2, readline
Runtime Dependencies: python_select
Platforms:            darwin
License:              PSF
Maintainers:          mcalhoun@macports.org, openmaintainer@macports.org

$ cd [proj source]
$ sudo python setup.py install 

$ python test.py 
Traceback (most recent call last):
  File "test.py", line 7, in <module>
    from magic import Magic, MagicException
  File "/Users/lee/Downloads/py_apps/python-magic/magic.py", line 128, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation
Lees-Box:python-magic lee$ python -c 'import magic'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "magic.py", line 128, in <module>
    raise ImportError('failed to find libmagic.  Check your installation')
ImportError: failed to find libmagic.  Check your installation

```

**Comment by DarkStar1** [comment]
@ahupp Thanks. This saved me time and a few hairs going grey
