### ISSUE TITLE
_cffi__xa0d5132dx54cebdac.c

### ISSUE THREAD

**Issue by francesco1119** [ahupp/python-magic#154]
Hello, my simple code written in `Python 3`  doesn't work on Windows 10:

```
#!/usr/bin/env python
# -*- coding: utf-8 -*-

import argparse
import magic
import os
import os.path

# Argparse starts here
parser = argparse.ArgumentParser()								
parser.add_argument('-input', dest='input',help="input one or more files",metavar=None)			
args = parser.parse_args()

input = args.input

file = magic.from_file(input)
print (file)
```

If I test it against a normal TXT file with 

`py Test.py -input TestMe.txt` 

it returns me: 

```
_cffi__xa0d5132dx54cebdac.c
C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic\__pycache__\_cffi__xa0d5132dx54cebdac.c(208): fatal error C1083: Cannot open include file: 'magic.h': No such file or directory
Traceback (most recent call last):
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\_msvccompiler.py", line 423, in compile
    self.spawn(args)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\_msvccompiler.py", line 542, in spawn
    return super().spawn(cmd)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\ccompiler.py", line 909, in spawn
    spawn(cmd, dry_run=self.dry_run)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\spawn.py", line 38, in spawn
    _spawn_nt(cmd, search_path, dry_run=dry_run)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\spawn.py", line 81, in _spawn_nt
    "command %r failed with exit status %d" % (cmd, rc))
distutils.errors.DistutilsExecError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cffi\ffiplatform.py", line 55, in _build
    dist.run_command('build_ext')
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\dist.py", line 974, in run_command
    cmd_obj.run()
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\setuptools\command\build_ext.py", line 75, in run
    _build_ext.run(self)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Cython\Distutils\old_build_ext.py", line 186, in run
    _build_ext.build_ext.run(self)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\command\build_ext.py", line 339, in run
    self.build_extensions()
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\Cython\Distutils\old_build_ext.py", line 194, in build_extensions
    self.build_extension(ext)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\setuptools\command\build_ext.py", line 196, in build_extension
    _build_ext.build_extension(self, ext)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\command\build_ext.py", line 533, in build_extension
    depends=ext.depends)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\distutils\_msvccompiler.py", line 425, in compile
    raise CompileError(msg)
distutils.errors.CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "Test.py", line 5, in <module>
    import magic
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic\__init__.py", line 1, in <module>
    from . import ffi
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\magic\ffi.py", line 27, in <module>
    ext_package="magic")
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cffi\api.py", line 437, in verify
    lib = self.verifier.load_library()
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cffi\verifier.py", line 113, in load_library
    self._compile_module()
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cffi\verifier.py", line 210, in _compile_module
    outputfilename = ffiplatform.compile(tmpdir, self.get_extension())
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cffi\ffiplatform.py", line 29, in compile
    outputfilename = _build(tmpdir, ext, compiler_verbose)
  File "C:\Users\franc\AppData\Local\Programs\Python\Python36-32\lib\site-packages\cffi\ffiplatform.py", line 62, in _build
    raise VerificationError('%s: %s' % (e.__class__.__name__, e))
cffi.ffiplatform.VerificationError: CompileError: command 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\BIN\\cl.exe' failed with exit status 2
```
Yes, Python Magic looks correctly installed:
![python3_installed](https://user-images.githubusercontent.com/3397477/33512736-5f11c866-d79a-11e7-89c2-246b87d075d0.PNG)

My Python version is the latest:
![latest](https://user-images.githubusercontent.com/3397477/33512766-7ab4edaa-d79a-11e7-9ebe-06277605ebb0.PNG)

**Comment by francesco1119** [comment]
Hello, it looks like I'm not the only one having this problem:

https://github.com/tyiannak/pyAudioAnalysis/issues/109

**Comment by ahupp** [comment]
I think you are using https://pypi.python.org/pypi/python-libmagic/0.4.0
not my package.

**Comment by francesco1119** [comment]
Sorry, you are right.
Taught `libmagic `was a part of your project. 
By the way `python-magic` is installed and as you can see the error is still there. It seems like it's a sort of incompatibility problem with Visual Studio

![complete error](https://user-images.githubusercontent.com/3397477/33523938-def481f8-d877-11e7-94d3-3aa773da9d9a.PNG)

**Comment by francesco1119** [comment]
I think is not a fault of your library but a Windows issue: 

https://github.com/TeamHG-Memex/sklearn-crfsuite/issues/10 

I suppose you mostly use your library under Linux and you never faced such a problem, right? 
I think we can close this ticket as there's no much you can do. 
Should I address this issue to Microsoft or Python?

**Comment by ahupp** [comment]
You probably have two packages with the name `magic`.  The magic/ffi.py file mentioned in the stack trace is not part of this package for sure.  Though you are right I've never used this on windows, all that was contributed by others.

**Comment by ahupp** [comment]
You need to remove python-libmagic.  That's causing the failure.  It's a different, similarly named project.

**Comment by francesco1119** [comment]
I uninstalled python-libmagic but now it's looking for it
![removed](https://user-images.githubusercontent.com/3397477/33540627-d0de083c-d930-11e7-917b-0e8dcb7d0b45.PNG)

**Comment by francesco1119** [comment]
And I'm just importing `magic 
![looking](https://user-images.githubusercontent.com/3397477/33540664-ffc824de-d930-11e7-887f-b55d1064ecbe.PNG)
`now

**Comment by francesco1119** [comment]
I found the solution: also for `Python 3` you need to install the 32bit bin file `python_magic_bin-0.4.14-py2.py3-none-win32.whl` from here

https://pypi.python.org/pypi/python-magic-bin/0.4.14

then python-magic magically works. 

![solution](https://user-images.githubusercontent.com/3397477/33590074-cc2a292c-d9e1-11e7-8ec0-9f45e4dd1a6c.PNG)


I suggest you to mention this for Windows 10 installations
