### ISSUE TITLE
MagicException: cannot allocate 2096567328 bytes (Cannot allocate memory)video/mp4

### ISSUE THREAD

**Issue by Superago86** [ahupp/python-magic#22]
When I want to know the mime type of big file, show in my console this error... what can i do to solve this problem?

thanks...

**Comment by BookGin** [comment]
I might encounter the same problem here. I'm using `python-magic==0.4.15` with Python 3.6.5. Here is the stack trace:

```
127.0.0.1:51590: GET https://pl11.live.panda.tv/live_panda/833a9b696db476a54c404158f9ab004b_3000.flv?sign=e7b3597f227b95cf70cbd3f683c17456&ts=5c7cb192&rid=-23208705

Addon error: Traceback (most recent call last):
  File "script.py", line 415, in response
    filetype = magic.from_buffer(file_content).lower()                                                                 
  File "/home/user/Desktop/dir/py3env/lib/python3.6/site-packages/magic.py", line 148, in from_buffer
    return m.from_buffer(buffer) 
  File "/home/user/Desktop/dir/py3env/lib/python3.6/site-packages/magic.py", line 82, in from_buffer
    return self._handle509Bug(e) 
  File "/home/user/Desktop/dir/py3env/lib/python3.6/site-packages/magic.py", line 101, in _handle509Bug
    raise e                      
  File "/home/user/Desktop/dir/py3env/lib/python3.6/site-packages/magic.py", line 80, in from_buffer
    return maybe_decode(magic_buffer(self.cookie, buf))
  File "/home/user/Desktop/dir/py3env/lib/python3.6/site-packages/magic.py", line 255, in magic_buffer
    return _magic_buffer(cookie, buf, len(buf))
  File "/home/user/Desktop/dir/py3env/lib/python3.6/site-packages/magic.py", line 188, in errorcheck_null
    raise MagicException(err)                                                                              
magic.MagicException: b'cannot allocate 7610961088 bytes (Cannot allocate memory)'
```

However I'm not sure what the file type is. I'll guess it's mp4 since it's from a streaming video website.

**Comment by ahupp** [comment]
It looks like this is coming from inside the libmagic library.  python-magic is just a wrapper for libmagic so we don't have control over that sort of allocation behavior.

**Comment by ahupp** [comment]
I'm closing because this appears to be in the underlying libmagic library.  You can report bugs in that library here: https://bugs.astron.com/
