### ISSUE TITLE
Some tests are failing.

### ISSUE THREAD

**Issue by Profpatsch** [ahupp/python-magic#53]
* Some unclosed files
* The date test doesn’t work in my time zone (UTC+2)
* Two file types are not recognized correctly

``` python
test.py:16: ResourceWarning: unclosed file <_io.BufferedReader name='testdata/magic.pyc'>
  value = m.from_buffer(open(filename, 'rb').read())
test.py:16: ResourceWarning: unclosed file <_io.BufferedReader name='testdata/test.gz'>
  value = m.from_buffer(open(filename, 'rb').read())
F.Ftest.py:16: ResourceWarning: unclosed file <_io.BufferedReader name='testdata/text-iso8859-1.txt'>
  value = m.from_buffer(open(filename, 'rb').read())
test.py:16: ResourceWarning: unclosed file <_io.BufferedReader name='testdata/text.txt'>
  value = m.from_buffer(open(filename, 'rb').read())
.F
======================================================================
FAIL: test_descriptions (__main__.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 43, in test_descriptions
    'text.txt': 'ASCII text',
  File "test.py", line 18, in assert_values
    self.assertEqual(value, expected_value_bytes)
AssertionError: b'gzip compressed data, was "test", from Unix, last modified: Sun Jun 29 03:32:52 2008' != b'gzip compressed data, was "test", from Unix, last modified: Sun Jun 29 01:32:52 2008'

======================================================================
FAIL: test_keep_going (__main__.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 71, in test_keep_going
    'application/octet-stream'.encode('utf-8'))
AssertionError: b'image/jpeg' != b'application/octet-stream'

======================================================================
FAIL: test_mime_types (__main__.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 31, in test_mime_types
    b'\xce\xbb': 'text/plain',
  File "test.py", line 18, in assert_values
    self.assertEqual(value, expected_value_bytes)
AssertionError: b'binary' != b'application/octet-stream'

----------------------------------------------------------------------
Ran 5 tests in 0.027s

FAILED (failures=3)
```

**Comment by ahupp** [comment]
The warnings and timezone issue are fixed.  I'm not sure about the other issues but suspect it's a libmagic problem.  I'm not in a position to debug this, if you are worried about it could you dig in?

**Comment by Profpatsch** [comment]
Ah, I don’t even know where I used python-magic in the past.

But glad to see the issue is mostly fixed.
