### ISSUE TITLE
test failure with python3 - test_mime_types (test.test.MagicTest) ... FAIL

### ISSUE THREAD

**Issue by jlec** [ahupp/python-magic#96]
```python
test_mime_types (test.test.MagicTest) ... FAIL

======================================================================
FAIL: test_keep_going (test.test.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/tmpfs/python-magic/test/test.py", line 79, in test_keep_going
    self.assertEqual(m.from_file(filename), 'image/jpeg'.encode('utf-8'))
AssertionError: b'image/jpeg\\012- application/octet-stream' != b'image/jpeg'

======================================================================
FAIL: test_mime_types (test.test.MagicTest)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/mnt/tmpfs/python-magic/test/test.py", line 36, in test_mime_types
    b'\xce\xbb': 'text/plain',
  File "/mnt/tmpfs/python-magic/test/test.py", line 23, in assert_values
    self.assertEqual(value, expected_value_bytes)
AssertionError: b'application/x-gzip' != b'application/gzip'

----------------------------------------------------------------------
Ran 5 tests in 0.019s

FAILED (failures=2)
```

**Comment by ahupp** [comment]
The test results vary depending on the specific build of magic and/or the magic db you have.  My reference machine is debian stable, YMMV.

**Comment by jlec** [comment]
So this means the software is supposed to only work on your machine?

**Comment by ahupp** [comment]
For better or worse, libmagic (for which this is just a wrapper) does not behave consistently across machines or versions.  I could extend the test cases to be version-specific but that seems like a losing battle.  I have no idea what's going on with your test results, but my guess is a libmagic install with a broken/bad magic db.
